#!/usr/bin/env python3
"""Promote direct panel writers using IDs derived from the stock DPF dispatch."""

from __future__ import annotations

import argparse
import csv
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from html import escape
from pathlib import Path
from typing import cast

HANDLER_PATTERN: re.Pattern[str] = re.compile(r"-> ([A-Za-z_][A-Za-z0-9_:~]*)")
FEATURE_LINE_PATTERN = re.compile(r"^(?P<indent>\s*)<feature\b.*?/>\s*$")
REQUIRED_DISPATCH_COLUMNS = {
    "id",
    "directions_proven",
    "argument_schema_recovered",
}
REQUIRED_WRITER_COLUMNS = {
    "name",
    "set_handler",
    "get_handler",
    "direction",
    "producer",
    "min",
    "max",
}
TEMPLATE_NOTICE = (
    "<!-- Registry template: writer IDs are derived from the stock dispatch map; "
    "do not package directly. -->"
)
GENERATED_NOTICE = (
    "<!-- Generated by tools/derive_writer_registry.py from the stock dispatch map; "
    "do not edit. -->"
)


class DerivationError(ValueError):
    """The supplied evidence cannot determine one unique registry output."""


@dataclass(frozen=True)
class WriterSpec:
    name: str
    set_handler: str
    get_handler: str
    direction: str
    producer: str
    minimum: str
    maximum: str


def _rows(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    try:
        with path.open(newline="", encoding="utf-8") as stream:
            reader = csv.DictReader(stream, delimiter="\t")
            if reader.fieldnames is None:
                raise DerivationError(f"{path}: missing header")
            return list(reader.fieldnames), list(reader)
    except (OSError, csv.Error) as error:
        raise DerivationError(f"{path}: cannot read TSV: {error}") from error


def _dispatch_handlers(path: Path) -> dict[str, set[int]]:
    header, rows = _rows(path)
    if not REQUIRED_DISPATCH_COLUMNS.issubset(header):
        raise DerivationError(f"{path}: incomplete dispatch header")
    if not rows:
        raise DerivationError(f"{path}: empty dispatch map")

    feature_ids: set[int] = set()
    handlers: dict[str, set[int]] = {}
    for row in rows:
        try:
            feature_id = int(row["id"])
        except ValueError as error:
            raise DerivationError(f"{path}: non-integer feature id {row['id']!r}") from error
        if feature_id in feature_ids:
            raise DerivationError(f"{path}: duplicate feature id {feature_id}")
        feature_ids.add(feature_id)
        evidence_handlers = cast(
            list[str], HANDLER_PATTERN.findall(row["argument_schema_recovered"])
        )
        for handler in evidence_handlers:
            handlers.setdefault(handler, set()).add(feature_id)
    return handlers


def _writer_specs(path: Path) -> list[WriterSpec]:
    header, rows = _rows(path)
    if set(header) != REQUIRED_WRITER_COLUMNS:
        raise DerivationError(f"{path}: writer header must be {sorted(REQUIRED_WRITER_COLUMNS)}")
    if not rows:
        raise DerivationError(f"{path}: empty writer specification")

    names: set[str] = set()
    specs: list[WriterSpec] = []
    for row in rows:
        name = row["name"]
        if not name or name in names:
            raise DerivationError(f"{path}: duplicate or empty writer name {name!r}")
        names.add(name)
        if row["direction"] not in {"set", "get", "both"}:
            raise DerivationError(f"{path}: invalid direction for {name}")
        if not row["set_handler"] and not row["get_handler"]:
            raise DerivationError(f"{path}: {name} has no evidence handler")
        specs.append(
            WriterSpec(
                name=name,
                set_handler=row["set_handler"],
                get_handler=row["get_handler"],
                direction=row["direction"],
                producer=row["producer"],
                minimum=row["min"],
                maximum=row["max"],
            )
        )
    return specs


def _derived_id(spec: WriterSpec, handlers: dict[str, set[int]]) -> int:
    evidence_handlers = tuple(
        handler for handler in (spec.set_handler, spec.get_handler) if handler
    )
    missing = tuple(handler for handler in evidence_handlers if handler not in handlers)
    if missing:
        raise DerivationError(f"{spec.name}: missing dispatch handler {', '.join(missing)}")
    ambiguous = {
        handler: sorted(handlers[handler])
        for handler in evidence_handlers
        if len(handlers[handler]) != 1
    }
    if ambiguous:
        raise DerivationError(f"{spec.name}: ambiguous dispatch handlers {ambiguous}")
    feature_ids = {next(iter(handlers[handler])) for handler in evidence_handlers}
    if len(feature_ids) != 1:
        raise DerivationError(
            f"{spec.name}: evidence handlers disagree on feature id {sorted(feature_ids)}"
        )
    return feature_ids.pop()


def _feature_line(indent: str, attributes: dict[str, str]) -> str:
    body = " ".join(f'{key}="{escape(value, quote=True)}"' for key, value in attributes.items())
    return f"{indent}<feature {body} />"


def derive_registry(template: Path, dispatch: Path, writers: Path, output: Path) -> None:
    handlers = _dispatch_handlers(dispatch)
    specs = _writer_specs(writers)
    promotions = {_derived_id(spec, handlers): spec for spec in specs}
    if len(promotions) != len(specs):
        raise DerivationError("multiple writer names derive to one feature id")

    try:
        root = ET.parse(template).getroot()
    except (OSError, ET.ParseError) as error:
        raise DerivationError(f"{template}: invalid registry XML: {error}") from error
    registry_ids = [int(row.attrib["id"]) for row in root.findall("feature")]
    if len(registry_ids) != len(set(registry_ids)):
        raise DerivationError(f"{template}: duplicate registry feature id")
    missing_rows = sorted(set(promotions) - set(registry_ids))
    if missing_rows:
        raise DerivationError(f"{template}: derived feature ids absent: {missing_rows}")

    rendered: list[str] = []
    promoted: set[int] = set()
    for line in template.read_text(encoding="utf-8").splitlines():
        if line == TEMPLATE_NOTICE:
            rendered.append(GENERATED_NOTICE)
            continue
        match = FEATURE_LINE_PATTERN.match(line)
        if match is None:
            rendered.append(line)
            continue
        element = ET.fromstring(line.strip())
        feature_id = int(element.attrib["id"])
        spec = promotions.get(feature_id)
        if spec is None:
            rendered.append(line)
            continue
        attributes = element.attrib
        attributes["name"] = spec.name
        attributes["direction"] = spec.direction
        attributes["handler"] = f"compiled-switch:{feature_id}:{spec.name}"
        attributes["producer"] = spec.producer
        attributes["status"] = "active"
        attributes["min"] = spec.minimum
        attributes["max"] = spec.maximum
        rendered.append(_feature_line(match.group("indent"), attributes))
        promoted.add(feature_id)
    if promoted != set(promotions):
        raise DerivationError(f"{template}: not all derived rows were rendered")

    output.parent.mkdir(parents=True, exist_ok=True)
    _ = output.write_text("\n".join(rendered) + "\n", encoding="utf-8")
    try:
        _ = ET.parse(output)
    except ET.ParseError as error:
        raise DerivationError(f"{output}: generated invalid XML: {error}") from error


def main() -> int:
    parser = argparse.ArgumentParser()
    _ = parser.add_argument("--template", type=Path, required=True)
    _ = parser.add_argument("--dispatch", type=Path, required=True)
    _ = parser.add_argument("--writers", type=Path, required=True)
    _ = parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        derive_registry(
            cast(Path, args.template),
            cast(Path, args.dispatch),
            cast(Path, args.writers),
            cast(Path, args.output),
        )
    except DerivationError as error:
        print(f"REFUSED: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
