/*
 * SPDX-FileCopyrightText: 2026 The LineageOS Project
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <aidl/vendor/oplus/hardware/subsys_interface/subsys_radio/BnSubsysRadioIndication.h>
#include <aidl/vendor/oplus/hardware/subsys_interface/subsys_radio/BnSubsysRadioResponse.h>

#include "PendingRequests.h"

namespace aidl::vendor::oplus::hardware::subsys_interface::subsys_radio {

class RadioResponse : public BnSubsysRadioResponse {
  public:
    explicit RadioResponse(::oplus::radio::PendingRequests& pending);

    ndk::ScopedAStatus backupNvBackupResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus configGsmTimingDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus configPaIcqDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus connectSarSensorResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus deleteEfsItemResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus deprioritizeNrResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus disconnectSarSensorResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus enableEndcResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus fetchOlogResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getAntForceStateByRatResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t enable) override;
    ndk::ScopedAStatus getAntIdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getAsdivFixPositionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t position) override;
    ndk::ScopedAStatus getAsdivStatesResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::AsdivState& data) override;
    ndk::ScopedAStatus getAvailableBandModesResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<int32_t>& bandModes) override;
    ndk::ScopedAStatus getBandResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int64_t result) override;
    ndk::ScopedAStatus getBandsTxNumResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getCABandComboResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& caInfo) override;
    ndk::ScopedAStatus getCallInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getCapabilityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t value) override;
    ndk::ScopedAStatus getDeviceLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getDeviceLockinfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& result) override;
    ndk::ScopedAStatus getDiagPktVersionMismatchDbResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::DiagPacketVersionMismatchDb& mismatchDb) override;
    ndk::ScopedAStatus getEchoLocateDlCarrierLogResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ElDlCellInfo& respInfo) override;
    ndk::ScopedAStatus getEchoLocateUlCarrierLogResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ElUlCellInfo& respInfo) override;
    ndk::ScopedAStatus getFiveGSaNsaModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getGpioStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t gpioInfo) override;
    ndk::ScopedAStatus getGsmPclPwrResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t pcl) override;
    ndk::ScopedAStatus getImsPolMgrApnResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::string& apn_name) override;
    ndk::ScopedAStatus getImsProfileApnResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::string& apn_name) override;
    ndk::ScopedAStatus getImsProfileListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& profileIndex) override;
    ndk::ScopedAStatus getImsUssdEnabledResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t imsUssdEnabled) override;
    ndk::ScopedAStatus getLtePowerClassResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, char16_t values) override;
    ndk::ScopedAStatus getModemBasebandVersionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::string& modemBaseband) override;
    ndk::ScopedAStatus getModemHeapInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::HeapInfo& heapInfo) override;
    ndk::ScopedAStatus getModemHeapListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::HeapList& heapList) override;
    ndk::ScopedAStatus getMotionStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& motionStates) override;
    ndk::ScopedAStatus getNasSysInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NasSysInfo& nasSysInfo) override;
    ndk::ScopedAStatus getNr5gBlerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t bler) override;
    ndk::ScopedAStatus getNr5gFullVoiceSupportResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t voiceSupport) override;
    ndk::ScopedAStatus getNrBandPreferResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& preferredBands) override;
    ndk::ScopedAStatus getNrServingCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NrCellInfo& result) override;
    ndk::ScopedAStatus getNrSupportResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t status) override;
    ndk::ScopedAStatus getNvBackupStatResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NvBackupStatisticsType& stat) override;
    ndk::ScopedAStatus getOperationModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode) override;
    ndk::ScopedAStatus getPhySlotStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::PhySlotStatus& slotInfo) override;
    ndk::ScopedAStatus getRfBandInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t activeBand, int32_t active1xChannel, int32_t activeEhrpdChannel) override;
    ndk::ScopedAStatus getRrcLogResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::RrcState& rrcState) override;
    ndk::ScopedAStatus getSarDsiStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t state) override;
    ndk::ScopedAStatus getSarRegionCodeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t code) override;
    ndk::ScopedAStatus getSarSnsDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t data) override;
    ndk::ScopedAStatus getServingCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CellInfo& result) override;
    ndk::ScopedAStatus getSimCardTypeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t type) override;
    ndk::ScopedAStatus getSimPathResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t simPath) override;
    ndk::ScopedAStatus getSimTrayStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<int32_t>& status) override;
    ndk::ScopedAStatus getSimlockActivateTimeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int64_t result) override;
    ndk::ScopedAStatus getSimlockCategoryDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& categoryData) override;
    ndk::ScopedAStatus getSimlockComboTypeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getSimlockCurrentRetryResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getSimlockDelayLockStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockFactoryResetTimeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int64_t result) override;
    ndk::ScopedAStatus getSimlockFeatureResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getSimlockFeeStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockFuseStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t secBootStatus, int8_t fuseStatus) override;
    ndk::ScopedAStatus getSimlockIsRegionVietnamResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::RsuSimlockLockStatus& lockStatus) override;
    ndk::ScopedAStatus getSimlockLockTypeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockLockmarkResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& result) override;
    ndk::ScopedAStatus getSimlockMaxRetryResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getSimlockOperatorIdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockRsuModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode) override;
    ndk::ScopedAStatus getSimlockSimStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockUnlockStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t result) override;
    ndk::ScopedAStatus getSimlockVersionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t minVersion, int8_t maxVersion) override;
    ndk::ScopedAStatus getSystemSelectionPreferenceResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SystemSelectionPreference& preference) override;
    ndk::ScopedAStatus getTestModeMaskResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int64_t result) override;
    ndk::ScopedAStatus getTxAdcResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getTxRxInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::TxRxInfo& txrxInfo) override;
    ndk::ScopedAStatus getVoiceConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::VoiceConfig& config) override;
    ndk::ScopedAStatus initRfPathResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus readEfsItemResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& result) override;
    ndk::ScopedAStatus readNvResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& result) override;
    ndk::ScopedAStatus refreshModemEfsResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus registerNr5gStatsEventResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus requireModemRebootResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus restoreNvBackupAllowedResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t allowed) override;
    ndk::ScopedAStatus restoreNvBackupResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendDciSyncReqAndRspResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& rspBuf) override;
    ndk::ScopedAStatus sendScreenStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAclStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAntForceStateByRatResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAntMaxPowerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAolScenarioResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAsdivFixPositionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setBandModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setBarCellResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCABandComboResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCalibrationStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCapabilityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCarrierOmacpFqdnResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setComboRfTxInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCyberSenseConfigPolicyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus setDiagnoseConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setFiveGSaNsaModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setGameScenario2RfResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setGpioStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setGsmPclPwrResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setMotionConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNr5gFullVoiceSupportResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNrBandPreferResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNvRestoreStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t state) override;
    ndk::ScopedAStatus setOosLpmCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setOperationModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPdcActivateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPdcDeactivateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRatAcqOrderResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRfDebugMaskResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRfTxInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRtSarModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRxChainsNumberResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRxDiversityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSarControlStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSarDsiStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSarRegionCodeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSarSensorChannelResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSarStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimPathResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimlockAccumulatedTimeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimlockActivateTimeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimlockFactoryResetTimeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimlockFeeStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setTestModeMaskResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setTimeZoneResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setUimPowerStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setUst5gUCConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setVoiceRoamingResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus testQlinkBlerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus testQlinkPingResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus testQlinkSlaveIdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus triggerModemCrashResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus unlockSimlockResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus updateKddiSimlockBlobResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus updateSimlockBlobResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus writeEfsItemResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus writeNvResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getRRCStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t rrcStatus) override;
    ndk::ScopedAStatus setBandPreferResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus getBandPreferResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& preferredBands) override;
    ndk::ScopedAStatus clearStoredFrequencyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus setSidoIssueConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setLteAcqScanDuringLteResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNWLimitStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t limitState) override;
    ndk::ScopedAStatus setDeviceIdleModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setDeviceDeepSleepResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setGameSpaceModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setIgnorePsPagingResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getEfsSpaceInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t availBlocks, int32_t blockSize, int32_t totalBlocks) override;
    ndk::ScopedAStatus getSimHotswapStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& hotswapStatus) override;
    ndk::ScopedAStatus getRfBandwidthInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t lteBandwidth, int32_t nrBandwidth) override;
    ndk::ScopedAStatus getRadioLinkInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& infoList) override;
    ndk::ScopedAStatus setMdmFeatureResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus resetModemConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setHstConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus updateFoldScreenStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus readSingleSimArrayResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& singleSimData) override;
    ndk::ScopedAStatus setMipiOscFreqHopStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNecReportPeriodResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNecConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNecDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setSimOverdueResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setLpmScanConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getCalibrationStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& adjustStatus) override;
    ndk::ScopedAStatus setMcfgRfsParamsResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t rfs_params_ver) override;
    ndk::ScopedAStatus getMcfgRfsParamsResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::McfgRfsParams& rfsParams) override;
    ndk::ScopedAStatus trigerMcfgRemoteDiscoverResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::McfgRemoteDiscoverInfo& mcfgRemoteDiscoverInfo) override;
    ndk::ScopedAStatus setRatScanResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setImeiSvnResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setUst5gUCBandConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setDssConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setDssAdditionalConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus readDssConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t config) override;
    ndk::ScopedAStatus readNRCAConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t config) override;
    ndk::ScopedAStatus setWhiteSANRCAConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setBlackSANRCAConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setWhiteNSANRCAConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus resetSANSAWhiteListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setTasForceIdxByRatResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<int32_t>& forceIdx) override;
    ndk::ScopedAStatus setMaxTxPowerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<int32_t>& txPowerConfig) override;
    ndk::ScopedAStatus lockCellAndBandResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus unlockCellAndBandResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setFastDormancyTimerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendFastDormancyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPSConformanceModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus queryFastDormancyModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode, int32_t profile) override;
    ndk::ScopedAStatus queryLegacyFastDormancyModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode) override;
    ndk::ScopedAStatus setServiceModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getServiceModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode) override;
    ndk::ScopedAStatus setCentricModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getCentricModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t mode) override;
    ndk::ScopedAStatus setCaStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getCaStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t status) override;
    ndk::ScopedAStatus setSyncWithApResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setBarCellOptResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getTxAntennaResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<int32_t>& antennas) override;
    ndk::ScopedAStatus setNwRateLimitingDetectCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNwRateLimitingInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NwRateLimitingInfo& limitInfo) override;
    ndk::ScopedAStatus getHwidResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t hwid) override;
    ndk::ScopedAStatus setRfTxPowerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus performPlmnUnblockResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus performPlmnBlockResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSaPriorityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPowerSavingStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus performLteAcqScanResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus plmnRatSelectionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus mdmDispatchCaseResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setImsRegTimerResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setMicroMotionStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus performBgSearchResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus clearForbiddenTaiResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setDataStallParamResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNfListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNfListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setL2nrSelectionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setLteDubiousCellResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setNrDubiousCellResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setMsimSubModePrefResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getMsimSubModeStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t msimSubMode, int32_t dsdaTxMode) override;
    ndk::ScopedAStatus getBwpConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t bwpState) override;
    ndk::ScopedAStatus setBwpConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNrcaConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int8_t nrcaState) override;
    ndk::ScopedAStatus setNrcaConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setBackgroundSearchResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendDeviceStateExtResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setOosCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setQrxlvminCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setArrearageCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSimTagResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setQosReportPeriodResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setQosConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getQosDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setDsdaPreferCustThreshResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setIdcOffsetResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus writeNvItemResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getLteCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t pci, int32_t arfcn, bool sib24Available) override;
    ndk::ScopedAStatus getNrcaInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NrcaInfo& nrcaInfo) override;
    ndk::ScopedAStatus updateDcdcSleepStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus enableCellBarringResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus configCellBarringParamResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setFeatureStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getFeatureStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t featureState) override;
    ndk::ScopedAStatus setRfTxInfo2Response(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAtcTableInitResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getTxCarkitResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& antennas) override;
    ndk::ScopedAStatus getServingCellularCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CellInfos& respInfo) override;
    ndk::ScopedAStatus startMetricsCollectResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus stopMetricsCollectResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getMetricsDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setHyperUplinkModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendSceneModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendQoeScoreResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setHyperUplinkParasResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setSiteCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setModemIndicationPolicyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getModemIndicationPolicyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::PolicyConfig>& policy) override;
    ndk::ScopedAStatus setAolStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setImbStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setMtplLimitStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAntFixStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAntBlockStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPowerBoostStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getModemProtocolInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus getAtomDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus loadAtomApplicationResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus unloadAtomApplicationResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getAllCellularCellInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CellInfos& servingCellInfo, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NeighborCellInfos& neighborCellInfos) override;
    ndk::ScopedAStatus setImsRtpInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setImsRtpThresholdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setRedirectOptSettingResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAttachPriorityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPingpongBarSettingResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus performRetHighRatResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getIndicationReportRecordsResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::IndReportRecord>& data) override;
    ndk::ScopedAStatus setCiwlanUiSwitchResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getATCIStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, bool enable) override;
    ndk::ScopedAStatus enableATCIPortResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setVonrRollbackCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus satelliteFirmwareDownLoadResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setEsimStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCarrierLockBlobResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCarrierLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getCarrierLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setRegionLockBlobResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setRegionLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus getRegionLockStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus writeEncryptedSerialIdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus readRegionLockDataResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus writeCarrierLockWhitelistResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus readCarrierLockWhitelistResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus setAtomStatusResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setImsAudioQualityThresholdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setPagingErrorCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAdaptiveHandoverThresholdResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setIndicationConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setEccListResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getQrxlvminCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::QrxlvminRspInfo& qrxlvminCfg) override;
    ndk::ScopedAStatus setSmartIdleCfgResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getPowerStatisticsResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::PowerStatisticsConfigs& powerStatistics) override;
    ndk::ScopedAStatus sendScoreInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendNetworkActionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus rollbackNetworkActionResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getNetworkActionStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t clientId, int32_t actionId, int32_t actionState) override;
    ndk::ScopedAStatus getSceneModeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SceneMode>& scenes) override;
    ndk::ScopedAStatus hplmnBgSearchResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getImsRtpRedunCapabilityResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t capability) override;
    ndk::ScopedAStatus syncImsRtpRedunDataPathConfigResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t result) override;
    ndk::ScopedAStatus exchangeImsRtpRedunPublicKeyResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsRtpRedunKeyRspInfo& keyRsp) override;
    ndk::ScopedAStatus setImsRtpRedunControlInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsRtpRedunControlRspInfo& controlRsp) override;
    ndk::ScopedAStatus dumpDiagMdLogBufferResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setMdLogBufferSizeResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setTxPathFilterResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setAtcTableDeInitResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getModemFittingInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ModemFittingInfo& mdInfo) override;
    ndk::ScopedAStatus getSatelliteImeiResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::string& imei3) override;
    ndk::ScopedAStatus setRxBoostStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getRxBoostStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::RxBoostStateInfo& stateInfo) override;
    ndk::ScopedAStatus getSatelliteCalibrationDataStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SatelliteCalDataStatusType& state) override;
    ndk::ScopedAStatus setWifiQosInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getWifiQosInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ModemWifiQosInfo>& wifiQosRspInfo) override;
    ndk::ScopedAStatus registerFenceClientResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t clientId) override;
    ndk::ScopedAStatus setFenceRecognizeStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getFenceStateResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::FenceStateInfo>& fenceStateInfo, bool state) override;
    ndk::ScopedAStatus triggerFenceLearningResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, int32_t fenceId) override;
    ndk::ScopedAStatus sendWifiConnectInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus sendFenceInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus deregisterFenceClientResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus setCallScoreInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info) override;
    ndk::ScopedAStatus getCallScoreInfoResponse(const ::aidl::vendor::oplus::hardware::subsys_interface::subsys::SubsysResponseInfo& info, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CallCellScore& score) override;

  private:
    ::oplus::radio::PendingRequests& pending_;
};

class RadioIndication : public BnSubsysRadioIndication {
  public:
    explicit RadioIndication(::oplus::radio::PendingRequests& pending);

    ndk::ScopedAStatus radioCyberSenseCellInfoInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CyberSenseHALCellInfo>& info) override;
    ndk::ScopedAStatus radioCyberSenseEventInd(int32_t type, int32_t value) override;
    ndk::ScopedAStatus radioDtmfStartInd(int32_t type, int8_t tone_type) override;
    ndk::ScopedAStatus radioDtmfStopInd(int32_t type, int8_t tone_type) override;
    ndk::ScopedAStatus radioImsMessageInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsMessage& imsMessage) override;
    ndk::ScopedAStatus radioImsRtpStateInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsRtpState& rtpState) override;
    ndk::ScopedAStatus radioLteCaInfoInd(int32_t type, const std::vector<int32_t>& ca_info) override;
    ndk::ScopedAStatus radioLteRegDomainInd(int32_t type, int32_t value) override;
    ndk::ScopedAStatus radioNecInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioNonddsPagingInd() override;
    ndk::ScopedAStatus radioNr5gDrxInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::Nr5gDrxType& info) override;
    ndk::ScopedAStatus radioNr5gFreqTypeIndication(int32_t type, int32_t nr5gFreqType) override;
    ndk::ScopedAStatus radioSimlockInfoChangedInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SimlockInfoType& info) override;
    ndk::ScopedAStatus radioSimlockStateChangedInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SimlockStateType& state) override;
    ndk::ScopedAStatus radioStateChanged(int32_t type, int32_t state) override;
    ndk::ScopedAStatus radioSidoIssueInd(int32_t type, const std::vector<int32_t>& params) override;
    ndk::ScopedAStatus radioNrCapInd(int32_t type, int8_t nr_cap) override;
    ndk::ScopedAStatus radioNonddsNullPagingInd(int32_t type, int8_t np_type, int32_t rat, int32_t errcode) override;
    ndk::ScopedAStatus radioCssnfNumInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioMipiOscFreqHopStateInd(int32_t type, int32_t value) override;
    ndk::ScopedAStatus radioSimOverdueInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SimOverdueIndType& state) override;
    ndk::ScopedAStatus radioNwRateLimitingInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NwRateLimitingInfo& limitInfo) override;
    ndk::ScopedAStatus radioMdmTestInd(int32_t type, int32_t data) override;
    ndk::ScopedAStatus radioMsimSubModeInd(int32_t type, int32_t msimSubMode, int32_t dsdaTxMode) override;
    ndk::ScopedAStatus radioQosPeriodReportInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioQosEventReportInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioLteCellInfoInd(int32_t type, int32_t pci, int32_t arfcn, bool sib24_available) override;
    ndk::ScopedAStatus radioMccChangeInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::MccChangeIndInfo& roamInfo) override;
    ndk::ScopedAStatus radioHstModeInd(int32_t type, int32_t hstMode) override;
    ndk::ScopedAStatus radioServingCellInfoInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CellInfos& info) override;
    ndk::ScopedAStatus radioHyperUplinkStateInd(int32_t type, int32_t sceneState, int32_t hyperUplinkState, int32_t hyperUplinkType) override;
    ndk::ScopedAStatus radioAtomDataInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioLinkLatencyInfoInd(int32_t type, int32_t ulLatency) override;
    ndk::ScopedAStatus radioImsRtpControlInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsRtpControlInfo& info) override;
    ndk::ScopedAStatus radioNasAccessBarringStatusInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NasAccessBarringStatusInfo& nasAccessBarringStatusinfo) override;
    ndk::ScopedAStatus radioNrcaInfoChangeInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NrcaInfo& nrcaInfo) override;
    ndk::ScopedAStatus radioVonrBackoffInfoChangeInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::VonrBackoffInfo& backoffInfo) override;
    ndk::ScopedAStatus radioVonrRollbackInfoChangeInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::VonrRollbackInfo& rollbackInfo) override;
    ndk::ScopedAStatus radioSingleSimChangeInd(int32_t type, int8_t status) override;
    ndk::ScopedAStatus radioCarrierLockStatusChangeInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioRegionLockStatusChangeInd(int32_t type, const std::vector<uint8_t>& data) override;
    ndk::ScopedAStatus radioAlertEventInd(int32_t type, int32_t alertId, int32_t alertCause, const std::vector<int32_t>& alertParam) override;
    ndk::ScopedAStatus radioVodataEventInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::VodataEventInfo& vodataEventInfo) override;
    ndk::ScopedAStatus radioAllCellInfoInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::CellInfos>& servingCellInfo, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::NeighborCellInfos>& neighborCellInfos) override;
    ndk::ScopedAStatus radioNetworkActionResultInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ActionResult>& result) override;
    ndk::ScopedAStatus radioSceneModeInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SceneMode>& scenes) override;
    ndk::ScopedAStatus radioSmartNetworkSelectInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::SmartNetworkSelectInfo& smartNetworkSelectInfo) override;
    ndk::ScopedAStatus radioImsRtpRedunEventInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::ImsRtpRedunEventInfo& event) override;
    ndk::ScopedAStatus rxBoostStateInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::RxBoostStateInfo& state) override;
    ndk::ScopedAStatus radioRrcStatusChangeInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::RrcStatusIndInfo& rrcInfo) override;
    ndk::ScopedAStatus radioFenceStateChangeInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::FenceStateInfo>& fenceStateInfos) override;
    ndk::ScopedAStatus radioFenceRemovedInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::FenceRemovedInfo>& fenceRemovedInfos) override;
    ndk::ScopedAStatus radioFenceMergedInd(int32_t type, const std::vector<::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::FenceMergedInfo>& fenceMergedInfos) override;
    ndk::ScopedAStatus radioFenceCreateInd(int32_t type, const ::aidl::vendor::oplus::hardware::subsys_interface::subsys_radio::FenceCreatedInfo& fenceCreatedInfo) override;

  private:
    ::oplus::radio::PendingRequests& pending_;
};

}  // namespace aidl::vendor::oplus::hardware::subsys_interface::subsys_radio
